#ifndef BP_STEREO_FROM_PYTHON_H
#define BP_STEREO_FROM_PYTHON_H
#define REF_IMAGE_FROM_PYTHON "conesH/im2.ppm"
#define TEST_IMAGE_FROM_PYTHON "conesH/im6.ppm"
#define SAVE_DISPARITY_IMAGE_PATH_GPU_FROM_PYTHON "conesH/computedDisparityMapTsukubaGPU.pgm"
#define SAVE_DISPARITY_IMAGE_PATH_CPU_FROM_PYTHON "conesH/computedDisparityMapTsukubaCPU.pgm"
#define SCALE_BP_FROM_PYTHON 2.0f
#define DEFAULT_GROUND_TRUTH_DISPARITY_FILE_FROM_PYTHON "conesH/disp2.pgm"
#define DEFAULT_GROUND_TRUTH_DISPARITY_SCALE_FROM_PYTHON 2.0f
#define NUM_POSSIBLE_DISPARITY_VALUES_FROM_PYTHON 127
#define ITER_BP_FROM_PYTHON 7
#define LEVELS_BP_FROM_PYTHON 6
#define DISC_K_BP_FROM_PYTHON 16.9333333333
#define DATA_K_BP_FROM_PYTHON 15.0f
#define LAMBDA_BP_FROM_PYTHON 0.1f
#define SIGMA_BP_FROM_PYTHON 0.7f
#define USE_SAME_ARRAY_FOR_ALL_LEVEL_MESSAGE_VALS_PYTHON 1
#define USE_SAME_ARRAY_FOR_ALL_ALLOC_PYTHON 1
#endif