#ifndef BP_STEREO_FROM_PYTHON_H
#define BP_STEREO_FROM_PYTHON_H
#define REF_IMAGE_FROM_PYTHON "cones/im2.ppm"
#define TEST_IMAGE_FROM_PYTHON "cones/im6.ppm"
#define SAVE_DISPARITY_IMAGE_PATH_GPU_FROM_PYTHON "cones/computedDisparityMapTsukubaGPU.pgm"
#define SAVE_DISPARITY_IMAGE_PATH_CPU_FROM_PYTHON "cones/computedDisparityMapTsukubaCPU.pgm"
#define SCALE_BP_FROM_PYTHON 4.0f
#define DEFAULT_GROUND_TRUTH_DISPARITY_FILE_FROM_PYTHON "cones/disp2.pgm"
#define DEFAULT_GROUND_TRUTH_DISPARITY_SCALE_FROM_PYTHON 4.0f
#define NUM_POSSIBLE_DISPARITY_VALUES_FROM_PYTHON 64
#define ITER_BP_FROM_PYTHON 7
#define LEVELS_BP_FROM_PYTHON 5
#define DISC_K_BP_FROM_PYTHON 8.53333333333
#define DATA_K_BP_FROM_PYTHON 15.0f
#define LAMBDA_BP_FROM_PYTHON 0.1f
#define SIGMA_BP_FROM_PYTHON 0.0f
#define CURRENT_DATA_TYPE_PROCESSING_FROM_PYTHON 1
#define CPU_OPTIMIZATION_SETTING_FROM_PYTHON 1
#define USE_OPTIMIZED_GPU_MEMORY_MANAGEMENT_FROM_PYTHON 1
#define OPTIMIZED_INDEXING_SETTING_FROM_PYTHON 1
#endif