#ifndef BP_STEREO_FROM_PYTHON_H
#define BP_STEREO_FROM_PYTHON_H
#define REF_IMAGE_FROM_PYTHON "teddyH/im2.ppm"
#define TEST_IMAGE_FROM_PYTHON "teddyH/im6.ppm"
#define SAVE_DISPARITY_IMAGE_PATH_GPU_FROM_PYTHON "teddyH/computedDisparityMapTsukubaGPU.pgm"
#define SAVE_DISPARITY_IMAGE_PATH_CPU_FROM_PYTHON "teddyH/computedDisparityMapTsukubaCPU.pgm"
#define SCALE_BP_FROM_PYTHON 2.0f
#define DEFAULT_GROUND_TRUTH_DISPARITY_FILE_FROM_PYTHON "teddyH/disp2.pgm"
#define DEFAULT_GROUND_TRUTH_DISPARITY_SCALE_FROM_PYTHON 2.0f
#define NUM_POSSIBLE_DISPARITY_VALUES_FROM_PYTHON 90
#define ITER_BP_FROM_PYTHON 20
#define LEVELS_BP_FROM_PYTHON 5
#define DISC_K_BP_FROM_PYTHON 2.0f
#define DATA_K_BP_FROM_PYTHON 20.0f
#define LAMBDA_BP_FROM_PYTHON 0.1f
#define SIGMA_BP_FROM_PYTHON 0.7f
#endif