from enum import Enum, auto

class BeliefPropParameterLocation(Enum):
	HEADER_FILE = auto()
	PARAMETERS_TEXT_FILE = auto()
	NOT_WRITTEN_TO_FILE = auto()

class RunConfigParams(Enum):
	
	REF_IMAGE = auto()
	TEST_IMAGE = auto()
	SAVE_DISPARITY_IMAGE_PATH_OPT_IMP = auto()
	SAVE_DISPARITY_IMAGE_PATH_DEFAULT_CPU_IMP = auto()
	SCALE_BP = auto()
	GROUND_TRUTH_DISPARITY_FILE_PATH = auto()
	GROUND_TRUTH_DISPARITY_SCALE = auto()
	NUM_POSSIBLE_DISPARITY_VALUES = auto()
	ITERS_BP = auto()
	LEVELS_BP = auto()
	DISC_K_BP = auto()
	DATA_K_BP = auto()
	LAMBDA_BP = auto()
	SIGMA_BP = auto()
	CURRENT_DATA_TYPE_PROCESSING = auto()
	CPU_OPTIMIZATION_SETTING = auto()
	USE_OPTIMIZED_GPU_MEMORY_MANAGEMENT = auto()
	BYTES_ALIGN_MEMORY = auto()
	NUM_DATA_ALIGN_WIDTH = auto()
	OPTIMIZED_INDEXING_SETTING = auto()
	NUM_OPENMP_THREADS = auto()

class RunConfigParameterLabels:

	RUN_CONFIG_PARAMS_LABELS = {}

	RUN_CONFIG_PARAMS_LABELS[REF_IMAGE] = "REF_IMAGE_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[TEST_IMAGE] = "TEST_IMAGE_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[SAVE_DISPARITY_IMAGE_PATH_OPT_IMP] = "SAVE_DISPARITY_IMAGE_PATH_OPT_IMP_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[SAVE_DISPARITY_IMAGE_PATH_DEFAULT_CPU_IMP] = "SAVE_DISPARITY_IMAGE_PATH_DEFAULT_CPU_IMP_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[SCALE_BP] = "SCALE_BP_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[GROUND_TRUTH_DISPARITY_FILE_PATH] = "GROUND_TRUTH_DISPARITY_FILE_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[GROUND_TRUTH_DISPARITY_SCALE] = "GROUND_TRUTH_DISPARITY_SCALE_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[NUM_POSSIBLE_DISPARITY_VALUES] = "NUM_POSSIBLE_DISPARITY_VALUES_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[ITERS_BP] = "ITER_BP_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[LEVELS_BP] = "LEVELS_BP_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[DISC_K_BP] = "DISC_K_BP_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[DATA_K_BP] = "DATA_K_BP_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[LAMBDA_BP] = "LAMBDA_BP_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[SIGMA_BP] = "SIGMA_BP_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[CURRENT_DATA_TYPE_PROCESSING] = "CURRENT_DATA_TYPE_PROCESSING_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[CPU_OPTIMIZATION_SETTING] = "CPU_OPTIMIZATION_SETTING_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[USE_OPTIMIZED_GPU_MEMORY_MANAGEMENT] = "USE_OPTIMIZED_GPU_MEMORY_MANAGEMENT_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[BYTES_ALIGN_MEMORY] = "BYTES_ALIGN_MEMORY_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[NUM_DATA_ALIGN_WIDTH] = "NUM_DATA_ALIGN_WIDTH_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[OPTIMIZED_INDEXING_SETTING] = "OPTIMIZED_INDEXING_SETTING_FROM_PYTHON"
	RUN_CONFIG_PARAMS_LABELS[NUM_OPENMP_THREADS] = "NUM_OPENMP_THREADS"

class ImageSets:

	tsukubaImageSet = {REF_IMAGE : "\"tsukuba/scene1.row3.col3.ppm\"", TEST_IMAGE : "\"tsukuba/scene1.row3.col4.ppm\"", SAVE_DISPARITY_IMAGE_PATH_OPT_IMP : "\"tsukuba/computedDisparityMapTsukubaGPU.pgm\"", SAVE_DISPARITY_IMAGE_PATH_DEFAULT_CPU_IMP : "\"tsukuba/computedDisparityMapTsukubaCPU.pgm\"", NUM_POSSIBLE_DISPARITY_VALUES : 16, SCALE_BP : 16.0, "GroundTruthDisp" : "\"tsukuba/truedisp.row3.col3.pgm\"", GROUND_TRUTH_DISPARITY_SCALE : 16.0, "bpLevelsImageSet" : 5}
	venusImageSet = {REF_IMAGE : "\"venus/im2.ppm\"", TEST_IMAGE : "\"venus/im6.ppm\"", SAVE_DISPARITY_IMAGE_PATH_OPT_IMP : "\"venus/computedDisparityMapTsukubaGPU.pgm\"", SAVE_DISPARITY_IMAGE_PATH_DEFAULT_CPU_IMP : "\"venus/computedDisparityMapTsukubaCPU.pgm\"", NUM_POSSIBLE_DISPARITY_VALUES : 21, SCALE_BP : 8.0, GROUND_TRUTH_DISPARITY_FILE_PATH : "\"venus/disp2.pgm\"", GROUND_TRUTH_DISPARITY_SCALE : 8.0, "bpLevelsImageSet" : 5}
	barn1ImageSet = {REF_IMAGE : "\"barn1/im2.ppm\"", TEST_IMAGE : "\"barn1/im6.ppm\"", SAVE_DISPARITY_IMAGE_PATH_OPT_IMP : "\"barn1/computedDisparityMapTsukubaGPU.pgm\"", SAVE_DISPARITY_IMAGE_PATH_DEFAULT_CPU_IMP : "\"barn1/computedDisparityMapTsukubaCPU.pgm\"", NUM_POSSIBLE_DISPARITY_VALUES : 32, SCALE_BP : 8.0, GROUND_TRUTH_DISPARITY_FILE_PATH : "\"barn1/disp2.pgm\"", GROUND_TRUTH_DISPARITY_SCALE : 8.0, "bpLevelsImageSet" : 5}
	conesImageSetQuarterSize = {REF_IMAGE : "\"cones/im2.ppm\"", TEST_IMAGE : "\"cones/im6.ppm\"", SAVE_DISPARITY_IMAGE_PATH_OPT_IMP : "\"cones/computedDisparityMapTsukubaGPU.pgm\"", SAVE_DISPARITY_IMAGE_PATH_DEFAULT_CPU_IMP : "\"cones/computedDisparityMapTsukubaCPU.pgm\"", NUM_POSSIBLE_DISPARITY_VALUES : 64, SCALE_BP : 4.0, GROUND_TRUTH_DISPARITY_FILE_PATH : "\"cones/disp2.pgm\"", GROUND_TRUTH_DISPARITY_SCALE : 4.0, "bpLevelsImageSet" : 5}
	conesImageSetHalfSize = {REF_IMAGE : "\"conesH/im2.ppm\"", TEST_IMAGE : "\"conesH/im6.ppm\"", SAVE_DISPARITY_IMAGE_PATH_OPT_IMP : "\"conesH/computedDisparityMapTsukubaGPU.pgm\"", SAVE_DISPARITY_IMAGE_PATH_DEFAULT_CPU_IMP : "\"conesH/computedDisparityMapTsukubaCPU.pgm\"", NUM_POSSIBLE_DISPARITY_VALUES : 128, SCALE_BP : 2.0, GROUND_TRUTH_DISPARITY_FILE_PATH : "\"conesH/disp2.pgm\"", GROUND_TRUTH_DISPARITY_SCALE : 2.0, "bpLevelsImageSet" : 5}

class RunConfigParameterLocations:

	RUN_CONFIG_PARAMS_LOCATIONS = {}

	# by default, location is in header file for now
	for param in RunConfigParams:
		RUN_CONFIG_PARAMS_LOCATIONS[param] = BeliefPropParameterLocation.HEADER_FILE

	RUN_CONFIG_PARAMS_LOCATIONS[NUM_OPENMP_THREADS] = BeliefPropParameterLocation.NOT_WRITTEN_TO_FILE

class RunConfigDefaultValues:

	IMAGE_SET_DEFAULT = ImageSets.tsukubaImageSet
	RUN_CONFIG_PARAMS_DEFAULT_VALUES = {}
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[REF_IMAGE] = ImageSets.tsukubaImageSet[REF_IMAGE]
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[TEST_IMAGE] = ImageSets.tsukubaImageSet[TEST_IMAGE]
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[SAVE_DISPARITY_IMAGE_PATH_OPT_IMP] = ImageSets.tsukubaImageSet[SAVE_DISPARITY_IMAGE_PATH_OPT_IMP]
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[SAVE_DISPARITY_IMAGE_PATH_DEFAULT_CPU_IMP] = ImageSets.tsukubaImageSet[SAVE_DISPARITY_IMAGE_PATH_DEFAULT_CPU_IMP]
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[SCALE_BP] = ImageSets.tsukubaImageSet[SCALE_BP]
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[GROUND_TRUTH_DISPARITY_FILE_PATH] = ImageSets.tsukubaImageSet[GROUND_TRUTH_DISPARITY_FILE_PATH]
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[GROUND_TRUTH_DISPARITY_SCALE] = ImageSets.tsukubaImageSet[GROUND_TRUTH_DISPARITY_SCALE]
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[NUM_POSSIBLE_DISPARITY_VALUES] = ImageSets.tsukubaImageSet[NUM_POSSIBLE_DISPARITY_VALUES]
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[LEVELS_BP] = ImageSets.tsukubaImageSet[LEVELS_BP]
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[ITERS_BP] = 7
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[DISC_K_BP] = 1.7
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[DATA_K_BP] = 15.0
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[LAMBDA_BP] = 0.1
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[SIGMA_BP] = 0.0
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[CURRENT_DATA_TYPE_PROCESSING] = 0
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[CPU_OPTIMIZATION_SETTING] = 0
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[USE_OPTIMIZED_GPU_MEMORY_MANAGEMENT] = 0
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[BYTES_ALIGN_MEMORY] = 0
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[NUM_DATA_ALIGN_WIDTH] = 0
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[OPTIMIZED_INDEXING_SETTING] = 1
	RUN_CONFIG_PARAMS_DEFAULT_VALUES[NUM_OPENMP_THREADS] = 1

