var annotated_dup =
[
    [ "beliefprop", "namespacebeliefprop.html", [
      [ "BpStereoSet", "structbeliefprop_1_1_bp_stereo_set.html", "structbeliefprop_1_1_bp_stereo_set" ],
      [ "BpLevelProperties", "structbeliefprop_1_1_bp_level_properties.html", "structbeliefprop_1_1_bp_level_properties" ],
      [ "BpLevel", "classbeliefprop_1_1_bp_level.html", "classbeliefprop_1_1_bp_level" ],
      [ "BpSettings", "structbeliefprop_1_1_bp_settings.html", "structbeliefprop_1_1_bp_settings" ]
    ] ],
    [ "run_environment", "namespacerun__environment.html", [
      [ "RunImpSettings", "structrun__environment_1_1_run_imp_settings.html", "structrun__environment_1_1_run_imp_settings" ]
    ] ],
    [ "BpFileHandling", "class_bp_file_handling.html", "class_bp_file_handling" ],
    [ "BpImage", "class_bp_image.html", "class_bp_image" ],
    [ "BpOnDevice", "struct_bp_on_device.html", "struct_bp_on_device" ],
    [ "BpParallelParams", "class_bp_parallel_params.html", "class_bp_parallel_params" ],
    [ "Convolve", "class_convolve.html", null ],
    [ "CPUThreadsPinnedToSocket", "class_c_p_u_threads_pinned_to_socket.html", "class_c_p_u_threads_pinned_to_socket" ],
    [ "DetailedTimings", "class_detailed_timings.html", "class_detailed_timings" ],
    [ "DisparityMap", "class_disparity_map.html", "class_disparity_map" ],
    [ "DisparityMapEvaluation", "class_disparity_map_evaluation.html", "class_disparity_map_evaluation" ],
    [ "DisparityMapEvaluationParams", "struct_disparity_map_evaluation_params.html", "struct_disparity_map_evaluation_params" ],
    [ "EvaluateAcrossRuns", "class_evaluate_across_runs.html", "class_evaluate_across_runs" ],
    [ "EvaluateBpImpResults", "class_evaluate_bp_imp_results.html", null ],
    [ "EvaluateImpResults", "class_evaluate_imp_results.html", "class_evaluate_imp_results" ],
    [ "FilterImage", "class_filter_image.html", "class_filter_image" ],
    [ "image", "classimage.html", "classimage" ],
    [ "InputSignature", "class_input_signature.html", "class_input_signature" ],
    [ "MemoryManagement", "class_memory_management.html", "class_memory_management" ],
    [ "MemoryManagementCUDA", "class_memory_management_c_u_d_a.html", "class_memory_management_c_u_d_a" ],
    [ "ParallelParams", "class_parallel_params.html", "class_parallel_params" ],
    [ "pnm_error", "classpnm__error.html", null ],
    [ "ProcessBp", "class_process_bp.html", "class_process_bp" ],
    [ "ProcessBpCUDA", "class_process_bp_c_u_d_a.html", "class_process_bp_c_u_d_a" ],
    [ "ProcessBpOptimizedCPU", "class_process_bp_optimized_c_p_u.html", "class_process_bp_optimized_c_p_u" ],
    [ "ProcessStereoSetOutput", "struct_process_stereo_set_output.html", "struct_process_stereo_set_output" ],
    [ "rgb", "structrgb.html", "structrgb" ],
    [ "RunBpImpMultInputs", "class_run_bp_imp_mult_inputs.html", "class_run_bp_imp_mult_inputs" ],
    [ "RunBpImpOnInput", "class_run_bp_imp_on_input.html", "class_run_bp_imp_on_input" ],
    [ "RunBpOnStereoSet", "class_run_bp_on_stereo_set.html", "class_run_bp_on_stereo_set" ],
    [ "RunBpOnStereoSetCUDA", "class_run_bp_on_stereo_set_c_u_d_a.html", "class_run_bp_on_stereo_set_c_u_d_a" ],
    [ "RunBpOnStereoSetOptimizedCPU", "class_run_bp_on_stereo_set_optimized_c_p_u.html", "class_run_bp_on_stereo_set_optimized_c_p_u" ],
    [ "RunBpStereoCPUSingleThread", "class_run_bp_stereo_c_p_u_single_thread.html", "class_run_bp_stereo_c_p_u_single_thread" ],
    [ "RunData", "class_run_data.html", "class_run_data" ],
    [ "RunImpMultInputs", "class_run_imp_mult_inputs.html", "class_run_imp_mult_inputs" ],
    [ "RunImpMultTypesAccels", "class_run_imp_mult_types_accels.html", "class_run_imp_mult_types_accels" ],
    [ "RunImpOnInput", "class_run_imp_on_input.html", "class_run_imp_on_input" ],
    [ "RunResultsSpeedups", "class_run_results_speedups.html", "class_run_results_speedups" ],
    [ "SmoothImage", "class_smooth_image.html", "class_smooth_image" ],
    [ "SmoothImageCPU", "class_smooth_image_c_p_u.html", "class_smooth_image_c_p_u" ],
    [ "SmoothImageCUDA", "class_smooth_image_c_u_d_a.html", "class_smooth_image_c_u_d_a" ]
];